# Generated by Django 4.1.1 on 2022-09-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryggve', '0002_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='affliation',
            field=models.CharField(default='Institute of Medical epidemiology and Biostatistics, Karolinska Institute', max_length=1000),
            preserve_default=False,
        ),
    ]
