# Generated by Django 4.1.1 on 2022-09-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tryggve', '0003_person_affliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='team_lead',
            field=models.BooleanField(default=False),
        ),
    ]
